#!/usr/bin/env bash

# Script to diff two directories of footprints and generate HTML diffs
#
# Adapted from kicad-library-utils/tools/gitlabci/visual_diff.sh
# => TODO: Refactor to extract common functionality?
set -ex

if [ -z "${KICAD_LIBRARY_UTILS}" ]; then
    echo "KICAD_LIBRARY_UTILS environment variable is not set"
    exit 1
fi

base_dir="$1"     # baseline/reference footprints
target_dir="$2"   # footprints generated by the current commit
output_dir="$3"   # output directory for the diffs

echo "Comparing $base_dir to $target_dir"

readarray -t changed_dirs < <(git diff --no-index --name-only "$base_dir" "$target_dir" | xargs --no-run-if-empty dirname | sort | uniq | grep '\.pretty$')

for target_path in "${changed_dirs[@]}"; do

    # Get the relative path to the target path from target_dir
    rel_target=$(realpath --relative-to="${target_dir}" "${target_path}")
    rel_base="${base_dir}/${rel_target}"
    # Strip the .pretty suffix, add .diff
    output_subdir="$output_dir/${rel_target%.*}.diff"

    echo "Diffing $rel_target against $target_path -> $output_subdir"

    python3 "${KICAD_LIBRARY_UTILS}/html-diff/src/html_diff.py" -j0 -v "$rel_base" "$target_path" -o "$output_subdir"
done

# Create the index HTML file
python3 "${KICAD_LIBRARY_UTILS}/html-diff/src/render_index_html.py" "$output_dir"
