import os
import sys
sys.path.insert(0, os.path.abspath('..'))  # Source code dir relative to this file

extensions = [
    'sphinx.ext.autodoc',       # Core library for html generation from docstrings
    'sphinx.ext.autosummary',   # Create neat summary tables
    'sphinx.ext.napoleon',      # For interpreting Google docstrings correctly
    #'sphinx_autodoc_typehints',# Uncomment for type alias (type 2)
    'sphinx_rtd_theme',         # Read the Docs theme
    'aafigure.sphinxext',       # For ASCII drawings
    'sphinx.ext.mathjax',       # For mathematical formulas
    'sphinx_math_dollar',       # To use the $ sign for inline mathematical expressions
    #'sphinx_toolbox.more_autodoc.typehints',
    'sphinx.ext.intersphinx',
    'sphinx.ext.inheritance_diagram',
]

# Turn on sphinx.ext.autosummary:
autosummary_generate = True

# Choose the "Read the Docs" theme:
html_theme = "sphinx_rtd_theme"

# Don't expand type definitions:
autodoc_typehints = "description"

#napoleon_preprocess_types = True
napoleon_use_param = True
#autodoc_type_aliases = {'Vec2DCompatible': ':data:`.Vec2DCompatible`'}  # Uncomment for type alias (type 2)
#autodoc_type_aliases = {'Vec2DCompatible': 'Vec2DCompatible'}  # Uncomment for type alias (type 1)
#typehints_fully_qualified = True
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}

autodoc_member_order = "groupwise"
#autoclass_content = "init"

# Prevent Sphinx from displaying the full path to a module:
add_module_names = False

# Add any paths that contain templates here, relative to this directory:
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'KiCad Library'
copyright = 'The KiCad Librarian Team'
author = 'The KiCad Librarian Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.2'
# The full version, including alpha/beta/rc tags.
release = '0.2'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Default options for ASCII figures (aafig extension):
aafig_default_options = dict(textual=True)


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'KiCad Libraray'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'library.tex', 'KiCad Library Documentation',
     'Thomas Pointhuber', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'library', 'KiCad',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'library', 'KiCad Library Documentation',
     author, 'KiCad Librarian Team', 'One line description of project.',
     'Miscellaneous'),
]
